default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", ENV["USER"]) %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: starter_development

test:
  <<: *default
  database: starter_test

production:
  primary:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || "starter_production" %>
  cache:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || "starter_production" %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || "starter_production" %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || "starter_production" %>_cable
    migrations_paths: db/cable_migrate
